replicaCount: 1

backend:
  image: shreybatra/sample-backend
  service:
    type: ClusterIP
    port: 8000
  env:
    REDIS_URI: redis://redis-svc:6379

frontend:
  image: shreybatra/sample-frontend
  service:
    type: NodePort
    port: 5175
    nodePort: 31000
  env:
    BACKEND_URL: http://backend-svc:8000

redis:
  image: redis
  service:
    type: ClusterIP
    port: 6379
  env:
    REDIS_PASSWORD: ""
